### ISSUE TITLE
Remove Docker Desktop dependency for Windows and Mac

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/dangerzone#118]
It would amazing if Dangerzone could be a standalone program without requiring the user to separately install Docker Desktop. Dangerzone relies on Linux containers though, and so Docker Desktop runs a Linux VM in order to run the containers in.

If we wanted to remove the Docker Desktop dependency we would have to figure out how to launch our own Linux VM in each OS. I think this would be a considerable amount of work and we would have to come up with a solution for each separate platform, but it would be a great improvement.

If we did this it would also make sense to switch from Docker to bubblewrap for Linux: #95 

### Further evidence / notes (added by @deeplow)

From user interviews, we learned that this was a painpoint for an ex-dangerzone user.

**Comment by micahflee** [comment]
We'll want to use this: https://www.mobyproject.org/

**Comment by micahflee** [comment]
I'm testing on macOS to start with. Specifically, we should use HyperKit to run the actual VM: https://github.com/moby/hyperkit and LinuxKit to create the VM image that runs: https://github.com/linuxkit/linuxkit

Installing LinuxKit:

```sh
brew tap linuxkit/linuxkit
brew install --HEAD linuxkit
```

Grab the linuxkit.yml file and build the image:

```sh
wget https://raw.githubusercontent.com/linuxkit/linuxkit/master/linuxkit.yml
linuxkit build linuxkit.yml
```

Now installing hyperkit (it's also easy to build from source):

```sh
brew install hyperkit
```

Then to run the VM:

```sh
hyperkit -f kexec,linuxkit-kernel
```

And it works!

```sh
$ hyperkit -f kexec,linuxkit-kernel                                                                              
Using fd 5 for I/O notifications
vmx_set_ctlreg: cap_field: 4 bit: 12 unspecified don't care: bit is 0
vmx_set_ctlreg: cap_field: 4 bit: 20 unspecified don't care: bit is 0
vmx_set_ctlreg: cap_field: 3 bit: 13 unspecified don't care: bit is 0
rdmsr to register 0x3a on vcpu 0
rdmsr to register 0x140 on vcpu 0
rdmsr to register 0x64d on vcpu 0
rdmsr to register 0x64e on vcpu 0
rdmsr to register 0x34 on vcpu 0
```

**Comment by micahflee** [comment]
I copy `linuxkit.yml` to `dangerzone.yml` and remove the nginx service, so here's my `dangerzone.yml`:

```yaml
kernel:
  image: linuxkit/kernel:5.10.39
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:78fb57c7da07c4e43c3a37b27755581da087a3b6
  - linuxkit/runc:bf1e0c61fb4678d6428d0aabbd80db5ea24e4d4d
  - linuxkit/containerd:cc02c2af9c928c2faeccbe4edc78bd297ad91866
  - linuxkit/ca-certificates:4df823737c9bf6a9564b736f1a19fd25d60e909a
onboot:
  - name: sysctl
    image: linuxkit/sysctl:02d2bd74509fd063857ceb4c4f502f09ee4f2e0a
  - name: dhcpcd
    image: linuxkit/dhcpcd:1033f340e2d42f86a60aab70752346f0045ea388
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
onshutdown:
  - name: shutdown
    image: busybox:latest
    command: ["/bin/echo", "so long and thanks for all the fish"]
services:
  - name: getty
    image: linuxkit/getty:ed32c71531f5998aa510847bb07bd847492d4101
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:bdabfe138f05f7d48396d2f435af16f5a6ccaa45
files:
  - path: etc/linuxkit-config
    metadata: yaml
trust:
  org:
    - linuxkit
    - library
```

Then build it:

```sh
linuxkit build -format kernel+initrd dangerzone.yml
```

Then run it:

```sh
linuxkit run hyperkit dangerzone
```

Now I get a shell inside the VM, but there doesn't seem to be a `/etc/containerd`. I can install it with:

```sh
apk add containerd
```

Now containerd is running, and looks like it's using `/run/containerd/containerd.sock` as a unix socket.

Also back on my host, the VM's state folder is called `dangerzone-state` and looks like there's a `connect` files in there that's also a unix socket.
