### ISSUE TITLE
Podman Desktop issues on macOS

### ISSUE THREAD

**Issue by almet** [freedomofpress/dangerzone#1187]
Reporting here an issue that  was originally posted by @jaxley in [#1127](https://github.com/freedomofpress/dangerzone/issues/1127#issuecomment-3009319629):

> I'm having what might be a similar issue with podman desktop on macos Intel silicon. Every conversion in Dangerzone fails with "unknown error 125"
> 
> It's not clear how I can see the debug output above to see if it's caused by the same issue or not.
> 
> Strangely, the issue ONLY seems to occur when the podman-machine-default is started within Podman desktop app. When I start it from the CLI via `podman machine start`, Dangerzone works fine. 
> 
> I thought maybe I'd see a difference in how the container was started but I compared the process listings for "podman" from desktop and CLI and they only differ by PID and time and tty.
> 
> ```shell
>   501 32337     1   0 11:03AM ttys000    0:00.05 /opt/homebrew/Cellar/podman/5.5.2/libexec/podman/gvproxy -mtu 1500 -ssh-port 55357 -listen-vfkit unixgram:///var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/podman-machine-default-gvproxy.sock -forward-dest /run/user/501/podman/podman.sock -forward-user core -forward-identity /Users/jaxley/.local/share/containers/podman/machine/machine -forward-sock /var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/podman-machine-default-api.sock -pid-file /var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/gvproxy.pid -log-file /var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/gvproxy.log
>   501 32338     1   0 11:03AM ttys000    0:00.04 /opt/homebrew/Cellar/podman/5.5.2/libexec/podman/vfkit --cpus 4 --memory 2048 --bootloader efi,variable-store=/Users/jaxley/.local/share/containers/podman/machine/applehv/efi-bl-podman-machine-default,create --device virtio-blk,path=/Users/jaxley/.local/share/containers/podman/machine/applehv/podman-machine-default-arm64.raw --device virtio-rng --device virtio-vsock,port=1025,socketURL=/var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/podman-machine-default.sock,listen --device virtio-serial,logFilePath=/var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/podman-machine-default.log --device rosetta,mountTag=rosetta,install --device virtio-net,unixSocketPath=/var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/podman-machine-default-gvproxy.sock,mac=5a:94:ef:e4:0c:ee --device virtio-fs,sharedDir=/Users,mountTag=a2a0ee2c717462feb1de2f5afd59de5fd2d8 --device virtio-fs,sharedDir=/private,mountTag=71708eb255bc230cd7c91dd26f7667a7b938 --device virtio-fs,sharedDir=/var/folders,mountTag=a0bb3a2c8b0b02ba5958b0576f0d6530e104 --device virtio-fs,sharedDir=/Applications/Dangerzone.app,mountTag=c768e727aefa7fe57f4c78d49d61dfd78820 --restful-uri tcp://localhost:55366
> ``` 

Thanks for opening an issue Jason! I have a few questions for you:

1. You're mentioning that you're running on Apple Intel Silicon, but I believe it needs to be one of intel OR silicon as they're two different architectures. Which one are you on?
2. I expect that you've followed the [dangerzone-podman guide](https://github.com/freedomofpress/dangerzone/blob/main/docs/podman-desktop.md)? Can you confirm?
3. When you run a conversion on the CLI (with `dangerzone `), with a `--debug` flag, do you see any other logs?
4. Can you run `podman machine info` after starting the machine from Podman Desktop (when you have the failure), and after starting it from the CLI (when it works)? That could hep us see if there are any discrepancies between the two configurations.

It seems that podman is not picking the correct VM, or re-configuring it when started from Podman Desktop rather than from the cli with `podman machine start`. I will have a look at that next week from a silicon m1 machine and report back here my findings.

Also, a note to tell you we're currently working on embedding podman desktop inside dangerzone (#1145) which should make these types of issues go away altogether.

**Comment by jaxley** [comment]
> Reporting here an issue that was originally posted by [@jaxley](https://github.com/jaxley) in [#1127](https://github.com/freedomofpress/dangerzone/issues/1127#issuecomment-3009319629):
> 
> > I'm having what might be a similar issue with podman desktop on macos Intel silicon. Every conversion in Dangerzone fails with "unknown error 125"
> > It's not clear how I can see the debug output above to see if it's caused by the same issue or not.
> > Strangely, the issue ONLY seems to occur when the podman-machine-default is started within Podman desktop app. When I start it from the CLI via `podman machine start`, Dangerzone works fine.
> > I thought maybe I'd see a difference in how the container was started but I compared the process listings for "podman" from desktop and CLI and they only differ by PID and time and tty.
> >   501 32337     1   0 11:03AM ttys000    0:00.05 /opt/homebrew/Cellar/podman/5.5.2/libexec/podman/gvproxy -mtu 1500 -ssh-port 55357 -listen-vfkit unixgram:///var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/podman-machine-default-gvproxy.sock -forward-dest /run/user/501/podman/podman.sock -forward-user core -forward-identity /Users/jaxley/.local/share/containers/podman/machine/machine -forward-sock /var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/podman-machine-default-api.sock -pid-file /var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/gvproxy.pid -log-file /var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/gvproxy.log
> >   501 32338     1   0 11:03AM ttys000    0:00.04 /opt/homebrew/Cellar/podman/5.5.2/libexec/podman/vfkit --cpus 4 --memory 2048 --bootloader efi,variable-store=/Users/jaxley/.local/share/containers/podman/machine/applehv/efi-bl-podman-machine-default,create --device virtio-blk,path=/Users/jaxley/.local/share/containers/podman/machine/applehv/podman-machine-default-arm64.raw --device virtio-rng --device virtio-vsock,port=1025,socketURL=/var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/podman-machine-default.sock,listen --device virtio-serial,logFilePath=/var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/podman-machine-default.log --device rosetta,mountTag=rosetta,install --device virtio-net,unixSocketPath=/var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/podman/podman-machine-default-gvproxy.sock,mac=5a:94:ef:e4:0c:ee --device virtio-fs,sharedDir=/Users,mountTag=a2a0ee2c717462feb1de2f5afd59de5fd2d8 --device virtio-fs,sharedDir=/private,mountTag=71708eb255bc230cd7c91dd26f7667a7b938 --device virtio-fs,sharedDir=/var/folders,mountTag=a0bb3a2c8b0b02ba5958b0576f0d6530e104 --device virtio-fs,sharedDir=/Applications/Dangerzone.app,mountTag=c768e727aefa7fe57f4c78d49d61dfd78820 --restful-uri tcp://localhost:55366
> 
> Thanks for opening an issue Jason! I have a few questions for you:
> 
> 1. You're mentioning that you're running on Apple Intel Silicon, but I believe it needs to be one of intel OR silicon as they're two different architectures. Which one are you on?

[jaxley] - lol - yes. Apple silicon - M1. #derp

> 2. I expect that you've followed the [dangerzone-podman guide](https://github.com/freedomofpress/dangerzone/blob/main/docs/podman-desktop.md)? Can you confirm?

Yes.

> 3. When you run a conversion on the CLI (with `dangerzone `), with a `--debug` flag, do you see any other logs?

```
/Applications/Dangerzone.app/Contents/MacOS/dangerzone-cli --debug ~/Downloads/safeware.pdf
╭──────────────────────────╮
│           ▄██▄           │
│          ██████          │
│         ███▀▀▀██         │
│        ███   ████        │
│       ███   ██████       │
│      ███   ▀▀▀▀████      │
│     ███████  ▄██████     │
│    ███████ ▄█████████    │
│   ████████████████████   │
│    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀    │
│                          │
│    Dangerzone v0.9.0     │
│ https://dangerzone.rocks │
╰──────────────────────────╯
Assigning ID '91ps1Z' to doc '/Users/jaxley/Downloads/safeware.pdf'

Converting document to safe PDF
> /opt/homebrew/bin/podman run --log-driver none --security-opt no-new-privileges --userns nomap --security-opt seccomp=/Applications/Dangerzone.app/Contents/Resources/share/seccomp.gvisor.json --cap-drop all --cap-add SYS_CHROOT --security-opt label=type:container_engine_t --network=none -u dangerzone -e RUNSC_DEBUG=1 --rm -i --name dangerzone-doc-to-pixels-91ps1Z dangerzone.rocks/dangerzone:20250331-0.9.0-0-gc99c424 /usr/bin/python3 -m dangerzone.conversion.doc_to_pixels
Conversion output (doc to pixels)
----- DOC TO PIXELS LOG START -----
Error: opening seccomp profile failed: open /Applications/Dangerzone.app/Contents/Resources/share/seccomp.gvisor.json: operation not permitted
----- DOC TO PIXELS LOG END -----
ERROR [doc 91ps1Z] 0% Unknown error code '125'

Failed to convert document(s)
```

Successful:

```
/Applications/Dangerzone.app/Contents/MacOS/dangerzone-cli --debug ~/Downloads/safeware.pdf
╭──────────────────────────╮
│           ▄██▄           │
│          ██████          │
│         ███▀▀▀██         │
│        ███   ████        │
│       ███   ██████       │
│      ███   ▀▀▀▀████      │
│     ███████  ▄██████     │
│    ███████ ▄█████████    │
│   ████████████████████   │
│    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀    │
│                          │
│    Dangerzone v0.9.0     │
│ https://dangerzone.rocks │
╰──────────────────────────╯
Assigning ID 'iDwP3J' to doc '/Users/jaxley/Downloads/safeware.pdf'

Converting document to safe PDF
> /opt/homebrew/bin/podman run --log-driver none --security-opt no-new-privileges --userns nomap --security-opt seccomp=/Applications/Dangerzone.app/Contents/Resources/share/seccomp.gvisor.json --cap-drop all --cap-add SYS_CHROOT --security-opt label=type:container_engine_t --network=none -u dangerzone -e RUNSC_DEBUG=1 --rm -i --name dangerzone-doc-to-pixels-iDwP3J dangerzone.rocks/dangerzone:20250331-0.9.0-0-gc99c424 /usr/bin/python3 -m dangerzone.conversion.doc_to_pixels
[doc iDwP3J] 0% Converting page 1/51 from pixels to PDF
[doc iDwP3J] 1% Converting page 2/51 from pixels to PDF
....
```

> 4. Can you run `podman machine info` after starting the machine from Podman Desktop (when you have the failure), and after starting it from the CLI (when it works)? That could hep us see if there are any discrepancies between the two configurations.

Successful:

```
% podman machine info
host:
    arch: arm64
    currentmachine: podman-machine-default
    defaultmachine: podman-machine-default
    eventsdir: /var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/storage-run-501/podman
    machineconfigdir: /Users/jaxley/.config/containers/podman/machine/applehv
    machineimagedir: /Users/jaxley/.local/share/containers/podman/machine/applehv
    machinestate: Running
    numberofmachines: 1
    os: darwin
    vmtype: applehv
version:
    apiversion: 5.5.2
    version: 5.5.2
    goversion: go1.24.4
    gitcommit: ""
    builttime: Tue Jun 24 07:41:45 2025
    built: 1750776105
    buildorigin: brew
    osarch: darwin/arm64
    os: darwin
```

Failure:

```
% podman machine info
host:
    arch: arm64
    currentmachine: podman-machine-default
    defaultmachine: podman-machine-default
    eventsdir: /var/folders/7d/jkbmd5t91q91kt_q2lqqd2k80000gn/T/storage-run-501/podman
    machineconfigdir: /Users/jaxley/.config/containers/podman/machine/applehv
    machineimagedir: /Users/jaxley/.local/share/containers/podman/machine/applehv
    machinestate: Running
    numberofmachines: 1
    os: darwin
    vmtype: applehv
version:
    apiversion: 5.5.2
    version: 5.5.2
    goversion: go1.24.4
    gitcommit: ""
    builttime: Tue Jun 24 07:41:45 2025
    built: 1750776105
    buildorigin: brew
    osarch: darwin/arm64
    os: darwin
```

> 
> It seems that podman is not picking the correct VM, or re-configuring it when started from Podman Desktop rather than from the cli with `podman machine start`. I will have a look at that next week from a silicon m1 machine and report back here my findings.
> 
> Also, a note to tell you we're currently working on embedding podman desktop inside dangerzone ([#1145](https://github.com/freedomofpress/dangerzone/issues/1145)) which should make these types of issues go away altogether.
